# Generated by Django 5.2 on 2026-05-21 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_clanstory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elder_name', models.CharField(max_length=200)),
                ('year_recorded', models.IntegerField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('transcript', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='elders_voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
