# Generated by Django 5.2 on 2026-05-21 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0005_migrationstory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Ceremony', 'Ceremony'), ('Ritual', 'Ritual'), ('Festival', 'Festival'), ('Food', 'Food'), ('Attire', 'Attire'), ('Oral Tradition', 'Oral Tradition'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.TextField()),
                ('year_originated', models.IntegerField(blank=True, null=True)),
                ('related_to', models.CharField(blank=True, help_text='Elder name or member ID', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
